//
// Generated file, do not edit! Created by nedtool 6.0 from inet/common/TimeTag.msg.
//

#ifndef __INET_TIMETAG_M_H
#define __INET_TIMETAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class CreationTimeTag;
class TimeTagBase;
class ElapsedTimeTag;
class DelayingTimeTag;
class QueueingTimeTag;
class ProcessingTimeTag;
class TransmissionTimeTag;
class PropagationTimeTag;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace inet {

/**
 * Class generated from <tt>inet/common/TimeTag.msg:24</tt> by nedtool.
 * <pre>
 * class CreationTimeTag extends TagBase
 * {
 *     simtime_t creationTime = simTime();
 * }
 * </pre>
 */
class INET_API CreationTimeTag : public ::inet::TagBase
{
  protected:
    omnetpp::simtime_t creationTime = simTime();

  private:
    void copy(const CreationTimeTag& other);

  protected:
    bool operator==(const CreationTimeTag&) = delete;

  public:
    CreationTimeTag();
    CreationTimeTag(const CreationTimeTag& other);
    virtual ~CreationTimeTag();
    CreationTimeTag& operator=(const CreationTimeTag& other);
    virtual CreationTimeTag *dup() const override {return new CreationTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(omnetpp::simtime_t creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CreationTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CreationTimeTag& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/common/TimeTag.msg:29</tt> by nedtool.
 * <pre>
 * class TimeTagBase extends TagBase
 * {
 *     string flowNames[];
 *     simtime_t totalTimes[];
 * }
 * </pre>
 */
class INET_API TimeTagBase : public ::inet::TagBase
{
  protected:
    omnetpp::opp_string *flowNames = nullptr;
    size_t flowNames_arraysize = 0;
    omnetpp::simtime_t *totalTimes = nullptr;
    size_t totalTimes_arraysize = 0;

  private:
    void copy(const TimeTagBase& other);

  protected:
    bool operator==(const TimeTagBase&) = delete;

  public:
    TimeTagBase();
    TimeTagBase(const TimeTagBase& other);
    virtual ~TimeTagBase();
    TimeTagBase& operator=(const TimeTagBase& other);
    virtual TimeTagBase *dup() const override {return new TimeTagBase(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setFlowNamesArraySize(size_t size);
    virtual size_t getFlowNamesArraySize() const;
    virtual const char * getFlowNames(size_t k) const;
    virtual void setFlowNames(size_t k, const char * flowNames);
    virtual void insertFlowNames(const char * flowNames);
    virtual void insertFlowNames(size_t k, const char * flowNames);
    virtual void eraseFlowNames(size_t k);
    virtual void setTotalTimesArraySize(size_t size);
    virtual size_t getTotalTimesArraySize() const;
    virtual omnetpp::simtime_t getTotalTimes(size_t k) const;
    virtual void setTotalTimes(size_t k, omnetpp::simtime_t totalTimes);
    virtual void insertTotalTimes(omnetpp::simtime_t totalTimes);
    virtual void insertTotalTimes(size_t k, omnetpp::simtime_t totalTimes);
    virtual void eraseTotalTimes(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimeTagBase& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimeTagBase& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/common/TimeTag.msg:35</tt> by nedtool.
 * <pre>
 * class ElapsedTimeTag extends TimeTagBase
 * {
 * }
 * </pre>
 */
class INET_API ElapsedTimeTag : public ::inet::TimeTagBase
{
  protected:

  private:
    void copy(const ElapsedTimeTag& other);

  protected:
    bool operator==(const ElapsedTimeTag&) = delete;

  public:
    ElapsedTimeTag();
    ElapsedTimeTag(const ElapsedTimeTag& other);
    virtual ~ElapsedTimeTag();
    ElapsedTimeTag& operator=(const ElapsedTimeTag& other);
    virtual ElapsedTimeTag *dup() const override {return new ElapsedTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ElapsedTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ElapsedTimeTag& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/common/TimeTag.msg:39</tt> by nedtool.
 * <pre>
 * class DelayingTimeTag extends TimeTagBase
 * {
 * }
 * </pre>
 */
class INET_API DelayingTimeTag : public ::inet::TimeTagBase
{
  protected:

  private:
    void copy(const DelayingTimeTag& other);

  protected:
    bool operator==(const DelayingTimeTag&) = delete;

  public:
    DelayingTimeTag();
    DelayingTimeTag(const DelayingTimeTag& other);
    virtual ~DelayingTimeTag();
    DelayingTimeTag& operator=(const DelayingTimeTag& other);
    virtual DelayingTimeTag *dup() const override {return new DelayingTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DelayingTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DelayingTimeTag& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/common/TimeTag.msg:43</tt> by nedtool.
 * <pre>
 * class QueueingTimeTag extends TimeTagBase
 * {
 * }
 * </pre>
 */
class INET_API QueueingTimeTag : public ::inet::TimeTagBase
{
  protected:

  private:
    void copy(const QueueingTimeTag& other);

  protected:
    bool operator==(const QueueingTimeTag&) = delete;

  public:
    QueueingTimeTag();
    QueueingTimeTag(const QueueingTimeTag& other);
    virtual ~QueueingTimeTag();
    QueueingTimeTag& operator=(const QueueingTimeTag& other);
    virtual QueueingTimeTag *dup() const override {return new QueueingTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const QueueingTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, QueueingTimeTag& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/common/TimeTag.msg:47</tt> by nedtool.
 * <pre>
 * class ProcessingTimeTag extends TimeTagBase
 * {
 * }
 * </pre>
 */
class INET_API ProcessingTimeTag : public ::inet::TimeTagBase
{
  protected:

  private:
    void copy(const ProcessingTimeTag& other);

  protected:
    bool operator==(const ProcessingTimeTag&) = delete;

  public:
    ProcessingTimeTag();
    ProcessingTimeTag(const ProcessingTimeTag& other);
    virtual ~ProcessingTimeTag();
    ProcessingTimeTag& operator=(const ProcessingTimeTag& other);
    virtual ProcessingTimeTag *dup() const override {return new ProcessingTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ProcessingTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ProcessingTimeTag& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/common/TimeTag.msg:51</tt> by nedtool.
 * <pre>
 * class TransmissionTimeTag extends TimeTagBase
 * {
 * }
 * </pre>
 */
class INET_API TransmissionTimeTag : public ::inet::TimeTagBase
{
  protected:

  private:
    void copy(const TransmissionTimeTag& other);

  protected:
    bool operator==(const TransmissionTimeTag&) = delete;

  public:
    TransmissionTimeTag();
    TransmissionTimeTag(const TransmissionTimeTag& other);
    virtual ~TransmissionTimeTag();
    TransmissionTimeTag& operator=(const TransmissionTimeTag& other);
    virtual TransmissionTimeTag *dup() const override {return new TransmissionTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransmissionTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransmissionTimeTag& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>inet/common/TimeTag.msg:55</tt> by nedtool.
 * <pre>
 * class PropagationTimeTag extends TimeTagBase
 * {
 * }
 * </pre>
 */
class INET_API PropagationTimeTag : public ::inet::TimeTagBase
{
  protected:

  private:
    void copy(const PropagationTimeTag& other);

  protected:
    bool operator==(const PropagationTimeTag&) = delete;

  public:
    PropagationTimeTag();
    PropagationTimeTag(const PropagationTimeTag& other);
    virtual ~PropagationTimeTag();
    PropagationTimeTag& operator=(const PropagationTimeTag& other);
    virtual PropagationTimeTag *dup() const override {return new PropagationTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PropagationTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PropagationTimeTag& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_TIMETAG_M_H

