//
// Generated file, do not edit! Created by nedtool 6.0 from inet/physicallayer/wireless/common/signal/Arrival.msg.
//

#ifndef __INET__PHYSICALLAYER_ARRIVAL_M_H
#define __INET__PHYSICALLAYER_ARRIVAL_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {
namespace physicallayer {

} // namespace physicallayer
} // namespace inet

#include "inet/common/geometry/Geometry_m.h" // import inet.common.geometry.Geometry

// cplusplus {{
#include "inet/physicallayer/wireless/common/signal/Arrival.h"
// }}


namespace inet {
namespace physicallayer {

} // namespace physicallayer
} // namespace inet

#endif // ifndef __INET__PHYSICALLAYER_ARRIVAL_M_H

