//
// Generated file, do not edit! Created by nedtool 6.0 from inet/protocolelement/aggregation/header/SubpacketLengthHeader.msg.
//

#ifndef __INET_SUBPACKETLENGTHHEADER_M_H
#define __INET_SUBPACKETLENGTHHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class SubpacketLengthHeader;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/protocolelement/aggregation/header/SubpacketLengthHeader.msg:24</tt> by nedtool.
 * <pre>
 * class SubpacketLengthHeader extends FieldsChunk
 * {
 *     chunkLength = B(2);
 *     b lengthField;
 * }
 * </pre>
 */
class INET_API SubpacketLengthHeader : public ::inet::FieldsChunk
{
  protected:
    b lengthField = b(-1);

  private:
    void copy(const SubpacketLengthHeader& other);

  protected:
    bool operator==(const SubpacketLengthHeader&) = delete;

  public:
    SubpacketLengthHeader();
    SubpacketLengthHeader(const SubpacketLengthHeader& other);
    virtual ~SubpacketLengthHeader();
    SubpacketLengthHeader& operator=(const SubpacketLengthHeader& other);
    virtual SubpacketLengthHeader *dup() const override {return new SubpacketLengthHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual b getLengthField() const;
    virtual void setLengthField(b lengthField);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SubpacketLengthHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SubpacketLengthHeader& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_SUBPACKETLENGTHHEADER_M_H

